### PR TITLE
Upgrade to v5

### PR DESCRIPTION
**Pull request by louisteenbrink**
Upgrade to liana v5 to benefit from the select all feature

### CODE REVIEW

**Review by rap2hpoutre — COMMENTED** [review]
According to the documentation (https://docs.forestadmin.com/documentation/v/inapp/how-tos/upgrade-to-v5), these lines should be updated:

https://github.com/ForestAdmin/forest-live-demo-rails/blob/9f6c601b05a6d0e83beb678a8c5ad6525970ea07/app/controllers/forest/companies_controller.rb#L13

To:

```ruby
emitter_company_id = ForestLiana::ResourcesGetter.get_ids_from_request(params)
```

**Review by rap2hpoutre — CHANGES_REQUESTED** [review]
There are some changes in `.forestadmin-schema.json` file, I don't know why (DISCLAIMER: I never tried the forest live demo for rails). I guess there should be no changes in actual schema (only a lib update).

Could you double check the database is synchronized with the one in production? (in other words, is it `address_line1` or `address_line_1`?)

**Comment by louisteenbrink** [comment]
@rap2hpoutre thanks. I've removed to forestadmin-schema and adapted the smart action according to the documentation

**Review by rap2hpoutre — APPROVED** [review]
🎉 Great! Thank you @louisteenbrink!  🎈 

_Side note: I reverted the `.forestadmin-schema.json` removal you made in last commit since it is not related to this actual PR. I prefer not changing anything to the current code base that is not related to liana version upgrade. Feel free to discuss if you feel like I'm wrong!_

**Pull request merged**
